import { AlertTriangle, CheckCircle2 } from 'lucide-react';
import type { ScenarioFileData } from '../../domain/dataFiles';
import { analyzeScenario } from '../../domain/scenarioValidation';

export default function ScenarioAuditPanel({ value, onSelectMission }: { value: ScenarioFileData; onSelectMission: (id: string) => void }) {
  const analysis = analyzeScenario(value.events, value.mapRegions, value.chains ?? [], value.clans, value.nClans);
  const errors = analysis.issues.filter(issue => issue.severity === 'ERROR').length;
  return <section className="space-y-4 rounded-xl border border-emerald-500/20 bg-[#0a0c0b] p-5">
    <div className="flex items-center gap-2"><AlertTriangle className="h-4 w-4 text-amber-400" /><h2 className="font-mono text-xs font-bold uppercase text-emerald-300">Проверка и баланс кампании</h2><span className={`ml-auto rounded px-2 py-1 font-mono text-[10px] ${errors ? 'bg-rose-500/15 text-rose-300' : 'bg-emerald-500/15 text-emerald-300'}`}>{errors ? `Ошибок: ${errors}` : 'Критических ошибок нет'}</span></div>
    {analysis.issues.length === 0 ? <p className="flex items-center gap-2 text-sm text-emerald-300"><CheckCircle2 className="h-4 w-4" />Сценарий прошёл автоматическую проверку.</p> : <div className="max-h-56 space-y-1 overflow-y-auto">{analysis.issues.map((issue, index) => <button key={`${issue.missionId}-${index}`} type="button" disabled={!issue.missionId} onClick={() => issue.missionId && onSelectMission(issue.missionId)} className={`block w-full rounded border p-2 text-left text-xs ${issue.severity === 'ERROR' ? 'border-rose-500/25 text-rose-300' : issue.severity === 'WARNING' ? 'border-amber-500/20 text-amber-300' : 'border-neutral-800 text-neutral-400'}`}>{issue.message}</button>)}</div>}
    <div className="overflow-x-auto"><table className="w-full min-w-[1040px] border-collapse text-right font-mono text-[10px] text-neutral-400"><thead><tr className="border-b border-neutral-800 text-neutral-600"><th className="p-2 text-left">День</th><th>Всего / квота</th><th>Операции</th><th>Сюжет</th><th>Пустышки</th><th>Этапы</th><th>Награда, h</th><th>Ресурсы</th><th>None</th><th>Лёгк.</th><th>Сред.</th><th>Тяж.</th><th>Экстр.</th><th>Невозм.</th></tr></thead><tbody>{analysis.days.map(day => <tr key={day.day} className="border-b border-neutral-900"><td className="p-2 text-left text-neutral-200">{day.day}</td><td>{day.events} / {value.nClans * 2}</td><td>{day.operations}</td><td>{day.stories}</td><td>{day.dummies}</td><td>{day.stages}</td><td>{day.autoRewardH}</td><td>{day.requiredResources}</td><td>{day.noResourceStages}</td><td>{day.easyChecks}</td><td>{day.mediumChecks}</td><td>{day.hardChecks}</td><td>{day.extremeChecks}</td><td>{day.impossibleChecks}</td></tr>)}</tbody></table></div>
    <p className="text-[10px] leading-relaxed text-neutral-600">Вероятности без ресурса для четырёх героев 1 уровня: DC 8 — 70%, DC 12 — 50%, DC 16 — 30%, DC 20 — 10%, DC 22+ — невозможно.</p>
  </section>;
}
